### ISSUE TITLE
204 no content

### ISSUE THREAD

**Issue by Metalzoid** [a-chacon/oas_rails#32]
Hey ! 

When I add a @response in my controller, I get this new response back but also the default 204 No content response.
However, my controller never returns a 204 No content. Is it possible to disable it?
I assume that this is the default response for display before any changes in the controller?

Edit: I discover the 204 No content is not return if i disable autodiscover_responses =)

**Comment by a-chacon** [comment]
Is that no enough? I was thinking about that after read the other comment. If there is not another idea then I just will close this issue.

This is because when this option is active and don't detect any render, then add the 204 response to the operation. And in your case you use a custom function for renders and OasRails cannot detect that (no renders detected).

**Comment by Metalzoid** [comment]
Oh yes, indeed, that is enough for me. But I think that in the future, having responses can disable the automatic 204, right?

**Comment by a-chacon** [comment]
mm could be. Like when there is at least one documented response, don't add the automatic detected responses?

**Comment by Metalzoid** [comment]
Yes, that's what I had in mind 😀

**Comment by a-chacon** [comment]
ok! I agree. Let this as an enhancement. I will be working on it!
